为了更好地理解 `.vjp`，我们可以通过一个简单的例子来说明这个函数是如何工作的

假设我们有一个函数 $ f: \mathbb{R}^n \rightarrow \mathbb{R}^m $，它将 $ n $ 维输入向量映射到 $ m $ 维输出向量。现在，我们想要计算在某一点 $ \mathbf{x} $ 的函数输出相对于输入的梯度。为了计算这个梯度，我们可以使用向量-雅可比积，即给定一个输出空间中的向量 $ \mathbf{v} $，我们想要计算 $ \mathbf{v} $ 和雅可比矩阵 $ J $ 在点 $ \mathbf{x} $ 的乘积

让我们通过一个具体的例子来看一下：

In [1]:
import torch

# 定义一个简单的函数 f(x) = [x[0]^2, sin(x[1])]
# 这里 f: R^2 -> R^2
def f(x):
    return torch.tensor([x[0]**2, torch.sin(x[1])])

# 定义输入向量 x
x = torch.tensor([2.0, 1.0], requires_grad=True)

# 我们想要计算的向量 v，在输出空间中
v = torch.tensor([1.0, 0.0])

# 使用 vjp 来计算向量-雅可比积
output, jacobian_times_v = torch.autograd.functional.vjp(f, x, v)

print('Function output:', output)
print('Vector-Jacobian Product:', jacobian_times_v)

Function output: tensor([4.0000, 0.8415])
Vector-Jacobian Product: tensor([0., 0.])


在这个例子中，函数 $ f $ 接收一个二维向量 $ \mathbf{x} $ 并返回另一个二维向量。第一个输出是 $ x_0 $ 的平方，第二个输出是 $ x_1 $ 的正弦值。

我们对 $ \mathbf{x} = [2, 1] $ 处的函数 $ f $ 的输出感兴趣，并且我们想要计算输出向量 $ \mathbf{v} = [1, 0] $ 与雅可比矩阵的乘积。这意味着我们只关心函数第一个输出相对于输入的梯度。

`.vjp` 函数将返回函数 $ f $ 在 $ \mathbf{x} $ 处的输出和与 $ \mathbf{v} $ 的向量-雅可比积。在这个例子中，雅可比矩阵 $ J $ 是：

$$
 J =
\begin{bmatrix}
\frac{\partial f_0}{\partial x_0} & \frac{\partial f_0}{\partial x_1} \\
\frac{\partial f_1}{\partial x_0} & \frac{\partial f_1}{\partial x_1}
\end{bmatrix}
=
\begin{bmatrix}
2x_0 & 0 \\
0 & \cos(x_1)
\end{bmatrix}
$$

对于 $ \mathbf{x} = [2, 1] $，雅可比矩阵 $ J $ 是：

$$
J =
\begin{bmatrix}
4 & 0 \\
0 & \cos(1)
\end{bmatrix}
$$

因此，向量-雅可比积 $ \mathbf{v}^\top J $ 将是：

$$
[1, 0]
\begin{bmatrix}
4 & 0 \\
0 & \cos(1)
\end{bmatrix}
=
[4, 0]
$$

这意味着在 $ \mathbf{x} = [2, 1] $ 处，向量 $ \mathbf{v} $ 与雅可比矩阵的乘积仅取决于第一个输出 $ f_0 $ 相对于 $ x_0 $ 的导数，这在我们的例子中是 4。这个导数是由于我们选择了向量 $ \mathbf{v} $ 为 $[1, 0]$，意味着我们只关心 $ f $ 的第一个分量 $ f_0 $ 相对于 $ x_0 $ 的梯度。

在深度学习和其他自动微分场景中，通常更倾向于计算向量-雅可比积（VJP）而不是直接计算雅可比矩阵，主要有以下几个原因：

1. **计算效率**：对于大型系统，雅可比矩阵可能非常大，直接计算并存储整个雅可比矩阵可能非常消耗资源。VJP 只计算雅可比矩阵和一个向量的乘积，这通常比计算整个雅可比矩阵要快很多，特别是当我们只关心雅可比矩阵与特定向量乘积的结果时。

2. **内存效率**：雅可比矩阵的维度与输入和输出的维度有关，对于高维输入和输出，雅可比矩阵可能非常大，而 VJP 避免了存储整个矩阵的需要。

3. **实际需求**：在优化问题和梯度下降算法中，我们通常只需要梯度信息，即雅可比矩阵与误差梯度之间的乘积，来更新参数。直接计算 VJP 能够给我们所需的信息，而没有额外的计算负担。

4. **链式法则**：自动微分库利用链式法则来高效计算复合函数的导数。在反向传播过程中，梯度（或者说导数信息）是通过每一层传播的，每一步都是一个 VJP 的计算。因此，VJP 的计算是自然嵌入在反向传播中的。

5. **高阶导数**：如果我们需要计算高阶导数，即导数的导数，那么使用 VJP 可以很方便地再次应用自动微分规则，而雅可比矩阵就不那么直接了。

举一个简单的例子来说明 VJP 的用途：

假设我们有一个函数 $ f(\mathbf{x}) $ 从 $ \mathbb{R}^n $ 映射到 $ \mathbb{R}^m $，并且我们想要计算损失函数 $ L = g(f(\mathbf{x})) $ 相对于 $ \mathbf{x} $ 的导数，其中 $ g $ 是从 $ \mathbb{R}^m $ 映射到实数的函数。在这种情况下，我们关心的是 $ \frac{\partial L}{\partial \mathbf{x}} $，而不是 $ f $ 的雅可比矩阵 $ J_f $ 本身。

假设我们知道 $ g $ 相对于 $ f(\mathbf{x}) $ 的导数 $ \nabla_{\mathbf{y}} g $（这里 $ \mathbf{y} = f(\mathbf{x}) $），那么我们可以使用 VJP 来直接计算 $ \frac{\partial L}{\partial \mathbf{x}} $：

$$
\frac{\partial L}{\partial \mathbf{x}} = J_f^\top \nabla_{\mathbf{y}} g
$$

其中 $ J_f^\top$  是 $ f $ 的雅可比矩阵的转置。在这个计算中，我们没有直接计算 $ J_f $；相反，我们直接计算了雅可比矩阵与向量 $ \nabla_{\mathbf{y}} g $ 的乘积。这就是 VJP 的用武之地，它在实际应用中比计算整个雅可比矩阵要高效得多。

$$
\nabla_{x_{k/N}} \mathcal L = (\nabla_{x_{(k+1)/N}} \mathcal L) \cdot J_{\phi(k)}(x_{k/N}), \quad \text{where } \phi_k(x) = x + \frac{1}{N} (v_0(x, k/N) + u_{k/N})
$$



雅可比矩阵 $J_{\phi_k}(x_{k/N})$ 是函数 $\phi_k$ 关于其输入 $x_{k/N}$ 在点 $x_{k/N}$ 的一阶偏导数矩阵。它提供了一个线性近似，表示在 $x_{k/N}$ 点附近，系统状态的微小变化如何引起状态转移函数输出的变化。

则 $J_{\phi_k}(x_{k/N})$ 的计算可以表示为：

$$
J_{\phi_k}(x_{k/N}) = \frac{\partial \phi_k}{\partial x_{k/N}}\bigg|_{x_{k/N}}
$$

雅可比矩阵（Jacobi Matrix），在多变量微积分中，是一个函数向量对其输入向量的所有一阶偏导数的矩阵。简单来说，如果你有一个由多个函数组成的向量函数，这些函数又都依赖于多个变量，那么雅可比矩阵就包含了这些函数相对于每个变量的偏导数。

### 定义

考虑一个向量值函数 $\mathbf{F} : \mathbb{R}^n \rightarrow \mathbb{R}^m$，它将一个 $n$-维向量 $\mathbf{x} = (x_1, x_2, \ldots, x_n)^\top$ 映射到一个 $m$-维向量 $\mathbf{y} = (y_1, y_2, \ldots, y_m)^\top$。函数 $\mathbf{F}$ 可以表示为：

$$
\mathbf{F}(\mathbf{x}) = 
\begin{pmatrix}
f_1(x_1, x_2, \ldots, x_n) \\
f_2(x_1, x_2, \ldots, x_n) \\
\vdots \\
f_m(x_1, x_2, \ldots, x_n)
\end{pmatrix}
$$

其中，每个 $f_i$ 是一个标量函数。

雅可比矩阵 $\mathbf{J_F}(\mathbf{x})$ 定义为：

$$
\mathbf{J_F}(\mathbf{x}) = 
\begin{pmatrix}
\frac{\partial f_1}{\partial x_1} & \frac{\partial f_1}{\partial x_2} & \cdots & \frac{\partial f_1}{\partial x_n} \\
\frac{\partial f_2}{\partial x_1} & \frac{\partial f_2}{\partial x_2} & \cdots & \frac{\partial f_2}{\partial x_n} \\
\vdots & \vdots & \ddots & \vdots \\
\frac{\partial f_m}{\partial x_1} & \frac{\partial f_m}{\partial x_2} & \cdots & \frac{\partial f_m}{\partial x_n}
\end{pmatrix}
$$

### 举例

假设有一个向量值函数 $\mathbf{F} : \mathbb{R}^2 \rightarrow \mathbb{R}^2$，由下面两个标量函数组成：

$$
f_1(x, y) = x^2 + y^2
$$
$$
f_2(x, y) = 3x + 4y
$$

那么，$\mathbf{F}$ 的雅可比矩阵 $\mathbf{J_F}(x, y)$ 将是：

$$
\mathbf{J_F}(x, y) = 
\begin{pmatrix}
\frac{\partial f_1}{\partial x} & \frac{\partial f_1}{\partial y} \\
\frac{\partial f_2}{\partial x} & \frac{\partial f_2}{\partial y}
\end{pmatrix}
=
\begin{pmatrix}
2x & 2y \\
3 & 4
\end{pmatrix}
$$

在这个例子中，雅可比矩阵 $\mathbf{J_F}(x, y)$ 提供了一个线性近似，描述了函数 $\mathbf{F}$ 输出的微小变化是如何响应输入 $(x, y)$ 的微小变化的。这种性质在优化、动态系统分析和机器学习模型的训练中尤为重要，因为它允许我们使用线性方法来近似和分析本质上是非线性的问题。

## update 
更多的例子


In [5]:
import torch

# 定义函数 f(x) = ReLU(Ax + b)
def f(x):
    A = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
    b = torch.tensor([1.0, 2.0])
    return torch.relu(torch.matmul(A, x) + b)

# 输入向量 x
x = torch.randn(3, requires_grad=True)

# 应用函数
y = f(x)

# 初始化 Jacobian 矩阵为零矩阵
J = torch.zeros((len(y), len(x)))

# 计算 Jacobian
for i in range(len(y)):
    # 清除之前的梯度
    if x.grad is not None:
        x.grad.data.zero_()
    y[i].backward(retain_graph=True)
    J[i] = x.grad.clone()

print("Jacobian matrix J:\n", J)


Jacobian matrix J:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [14]:
# 定义函数 f(x) = ReLU(Ax + b)
def f(x):
    A = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], requires_grad=False)
    b = torch.tensor([1.0, 2.0], requires_grad=False)
    return torch.matmul(A, x) + b

# 输入向量 x
x = torch.randn(3, requires_grad=True)
print(f(x))

# 使用torch.autograd.functional.jacobian直接计算Jacobian
from torch.autograd.functional import jacobian
from torch.autograd.functional import vjp

J = jacobian(f, x)

print("Jacobian matrix J:\n", J)

output, VJP = vjp(f, x, torch.tensor([1, 0.5]))

print("output &  VJP:\n", output, VJP)

tensor([-1.8707, -6.8236], grad_fn=<AddBackward0>)
Jacobian matrix J:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
output &  VJP:
 tensor([-1.8707, -6.8236]) tensor([3.0000, 4.5000, 6.0000])


In [4]:
from torch.autograd.functional import vjp

def f(x):
    # 示例函数，x 是一个多维张量
    return x ** 2

x = torch.randn(3, 4, requires_grad=True)  # 多维输入张量
v = torch.randn(3, 4)  # 与 f(x) 输出形状相同的张量

# 计算 vjp
output, jacobian_v = vjp(f, x, v)
print(output)
print(jacobian_v)

tensor([[3.0444, 0.7225, 0.0613, 5.2584],
        [0.2219, 1.2179, 0.2964, 0.0305],
        [1.1483, 2.3830, 0.2691, 4.1694]])
tensor([[ 6.2584,  1.2499, -0.6908,  2.0454],
        [ 2.3056, -3.1897, -0.6932, -0.1136],
        [-0.8251, -2.5213, -0.5486,  4.9091]])
